
/**************************************************************
 *	
 *	aNewWorld, 8 bit, 11025Hz,
 *	1 channel, 717120 bytes/channel
 *	Total Size: 1 * 717120 + 4 (header) = 717164 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nick Sinclair.NICK-PC\Google Drive\School\Georgia Tech 2016-2020\CS 2261\Milestone04\aNewWorld.wav
 *	Time-stamp: Sun Nov 25 22:42:50 2018
 *	
 **************************************************************/

#ifndef __ANEWWORLDH__
#define __ANEWWORLDH__

#define ANEWWORLDFREQ 11025
#define ANEWWORLDLEN 717120

extern const unsigned char aNewWorld[717120];

#endif /* __ANEWWORLDH__ */
