
/**************************************************************
 *	
 *	corridor, 8 bit, 11025Hz,
 *	1 channel, 785376 bytes/channel
 *	Total Size: 1 * 785376 + 4 (header) = 785420 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nick Sinclair.NICK-PC\Google Drive\School\Georgia Tech 2016-2020\CS 2261\Milestone04\corridor.wav
 *	Time-stamp: Sun Nov 25 22:34:48 2018
 *	
 **************************************************************/

#ifndef __CORRIDORH__
#define __CORRIDORH__

#define CORRIDORFREQ 11025
#define CORRIDORLEN 785376

extern const unsigned char corridor[785376];

#endif /* __CORRIDORH__ */
