
/**************************************************************
 *	
 *	keyGrab, 8 bit, 11025Hz,
 *	1 channel, 19840 bytes/channel
 *	Total Size: 1 * 19840 + 4 (header) = 19884 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nick Sinclair.NICK-PC\Google Drive\School\Georgia Tech 2016-2020\CS 2261\Milestone04\keyGrab.wav
 *	Time-stamp: Wed Nov 28 17:06:00 2018
 *	
 **************************************************************/

#ifndef __KEYGRABH__
#define __KEYGRABH__

#define KEYGRABFREQ 11025
#define KEYGRABLEN 19840

extern const unsigned char keyGrab[19840];

#endif /* __KEYGRABH__ */
