
/**************************************************************
 *	
 *	openDoor, 8 bit, 11025Hz,
 *	1 channel, 13465 bytes/channel
 *	Total Size: 1 * 13465 + 4 (header) = 13509 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nick Sinclair.NICK-PC\Google Drive\School\Georgia Tech 2016-2020\CS 2261\Milestone04\openDoor.wav
 *	Time-stamp: Wed Nov 28 09:17:50 2018
 *	
 **************************************************************/

#ifndef __OPENDOORH__
#define __OPENDOORH__

#define OPENDOORFREQ 11025
#define OPENDOORLEN 13465

extern const unsigned char openDoor[13465];

#endif /* __OPENDOORH__ */
