
/**************************************************************
 *	
 *	succ, 8 bit, 11025Hz,
 *	1 channel, 12803 bytes/channel
 *	Total Size: 1 * 12803 + 4 (header) = 12847 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nick Sinclair.NICK-PC\Google Drive\School\Georgia Tech 2016-2020\CS 2261\Milestone04\succ.wav
 *	Time-stamp: Wed Nov 28 17:06:11 2018
 *	
 **************************************************************/

#ifndef __SUCCH__
#define __SUCCH__

#define SUCCFREQ 11025
#define SUCCLEN 12803

extern const unsigned char succ[12803];

#endif /* __SUCCH__ */
