
/**************************************************************
 *	
 *	turningTheScrew, 8 bit, 11025Hz,
 *	1 channel, 2469888 bytes/channel
 *	Total Size: 1 * 2469888 + 4 (header) = 2469932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nick Sinclair.NICK-PC\Google Drive\School\Georgia Tech 2016-2020\CS 2261\Milestone04\turningTheScrew.wav
 *	Time-stamp: Sun Nov 25 22:22:41 2018
 *	
 **************************************************************/

#ifndef __TURNINGTHESCREWH__
#define __TURNINGTHESCREWH__

#define TURNINGTHESCREWFREQ 11025
#define TURNINGTHESCREWLEN 2469888

extern const unsigned char turningTheScrew[2469888];

#endif /* __TURNINGTHESCREWH__ */
